all: compile_main

compile_main:
	@gcc -g fsdriver3.c fsHigh.c dirEntryControlUtil_dir_main.c dirEntryControlUtil_dir_sec.c  dirEntryControlUtil_file_main.c dirEntryControlUtil_file_sec.c bitMapUtil.c  fsLow.c -lm -o fsdriver
